[package]
name = "kirbynes"
version = "1.0.0"
authors = ["Wilfried Rabouin"]
edition = "2015"

[features]
default = []
trace = []

[dependencies]
minifb = "0.15.3"
log = "0.4.8"
simple_logger = "1.6.0"
