[package]
name = "kirbynes"
version = "1.0.0"
authors = ["Wilfried Rabouin"]
edition = "2015"

[features]
default = []
trace = []

[dependencies]
minifb = "0.19.0"
log = "0.4.11"
simple_logger = "1.9.0"
