name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check
      run: cargo check --features "trace debugger" --tests --verbose
    - name: Test
      run: cargo test --release --features "fullspeed" --verbose
