name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --features "trace nametable-viewer benchmark" --tests --verbose
    - name: Run tests
      run: cargo test --release --verbose
    - name: Compare logs
      run: cargo test --release --verbose --features trace nestest_trace 
